name: ci.golang
on:
  push:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./golang

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Test all
        run: make test
        timeout-minutes: 4

  golangci:
    name: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./golang

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.62.2
          args: --timeout 3m --verbose
